### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by RaymondMRose** [simondavies/Veezi-API-Wrapper#1]
When I require this through composer, I'm getting Class 'VeeziAPI\Services\APIRequest' not found in '...vendor/simondavies/veezi-api-wrapper/App/VeeziAPI/VeeziAPIWrapper.php.'

I'm very new to Composer but I got other packages to work. Just not yours.

This is for a website that I've built for a local movie theater.

**Comment by simondavies** [comment]
Hi thanks for this, currently off machine to verify, will get to look st it as soon as I can, sorry for delay

**Comment by RaymondMRose** [comment]
Thanks so much!

**Comment by simondavies** [comment]
Just having a quick test before i get some  zzzzz, I have set up a new folder and run a `composer  init`, then I run the following:

```
composer require simondavies/veezi-api-wrapper
```

This then installed without issue.

I have however marked it with a release version, so this might also be able to help.

But can you let me know, how your compoer looks and if your using this as the inital project or within a current one.

It looks like i have missed the create project method on the read me docs.

So run the following to init as the main project:

```
composer create-project simondavies/veezi-api-wrapper
```

But if you let  me know so I can then look into this further for you.

**Comment by RaymondMRose** [comment]
I'm still having the same issue:

Fatal error: Class 'VeeziAPI\Services\APIRequest' not found in /home/btownstate/public_html/wp-content/plugins/cwt-veezi/vendor/simondavies/veezi-api-wrapper/App/VeeziAPI/VeeziAPIWrapper.php on line 20

No matter how I install it, I keep getting the same error.

**Comment by RaymondMRose** [comment]
I figured it out!

You have a folder marked "services" that should be capitalized "Services."

Now it works!

**Comment by simondavies** [comment]
Thats great to hear, seems like a case sensitive server etc, thats stung me many at time.  Will correct, the issue. thanks again.
