### ISSUE TITLE
Pull movies and sort by date

### ISSUE THREAD

**Issue by TheNewGuy16** [simondavies/Veezi-API-Wrapper#10]
Sorry one more wall for me to get over is there a way to list movies by date?  do you set u a new function in the VeeziAPIWrapper.php? or something in the APIRequest.php.  I am trying to find what request action the api uses to get all future movies. I see you reference the 'film' action to get the films in the film listing but what would it be for all the movies for the future sorted by dates is it the 'sessions' action?

**Comment by simondavies** [comment]
Hi, are talking about listing films by date rather than by film?

For eg this is some thing i did for this site [Film Listing by date](https://www.peckhamplex.london/film/listings)

If so i'll have to get back to you.

**Comment by TheNewGuy16** [comment]
Yes that is exactly what I want can you put an example in the files here so I can see how you are pulling them in?

**Comment by TheNewGuy16** [comment]
I did get the sessions and date ids to populate but again this api stuff is new to me

**Comment by simondavies** [comment]
I wont be able to put an example here as it can be a lot etc but will try and explain how I did it.

**Comment by TheNewGuy16** [comment]
sweet that would be awesome. I just cant figure out how to pull the dates in and then find the movies that are associated with that date....i can get the sessions to populate but I am not sure if that's how you do it.

**Comment by simondavies** [comment]
Hopefully the following will help.

basically I loop through all the films and then put them in to dated arrays that are created by the films itself.

```php

public function getAllAvailableFilmsByDate() {
    // -- Basically i get all the 'websession'
    $film_details = self::getAllWebSessions();
    $film_dates = [];
    //-- then I loop through them
    foreach ($film_details as $film) {
        //-- I then create carbon to create a date instance to help
        //- create the dates array
        $PreShowStartTime = Carbon::parse($film->PreShowStartTime);
        $day = $PreShowStartTime->format('l jS F Y');
        $time = $PreShowStartTime->format('H:i');
        $data = [
            'id' => $film->FilmId,
            'title' => $film->Title,
            //-- add what ever data you want with each film
            ....
        ];
        //-- Sort them into their restropective film Dates
        //-- As you can see im using the $day variable to create the array key
        //-- this then sorts them into days
        if (array_key_exists($day, $film_dates)) {
            $film_dates[$day][] = $data;
        } else {
            $film_dates[$day][] = $data;
        }

        //-- I then sort the array/result by the key
        //-- So its sorting by date.
        uksort($film_dates, function ($a, $b) {
            return strtotime($a) - strtotime($b);
        });

        //-- sort the films into their titles on the day and their bookable times/links
        return self::orderTheFilmsIntoTimes($film_dates);

    }
}


public function orderTheFilmsIntoTimes($dates) {
    $day = [];
    $film_times = [];
    $count = 0;

    //-- loop through the day
    foreach ($dates as $date => $films) {
        //-- loop through films on that day
        foreach ($films as $film_index => $film) {
            $film_details = [
                'title' => $film['title'],
                'url' => $film['url'],
                'time' => $film['time'],
                ...
            ];

            //-- if title created then just add to it else create it first
            if (array_key_exists($date, $film_details)) {
                array_push($film_times[$film['id']], $film_details);
            } else {
                $film_times[$film['id']][] = $film_details;
            }
        }
        $day[$date] = $film_times;
        $film_times = [];
    }
    return $day;
}
```

**Comment by TheNewGuy16** [comment]
Is this a new controller in the film repositories folder or are these new
public function in the VeeziAPIWrapper.php?

**Comment by simondavies** [comment]
So then the second function then sorted the films on those days into their own group and then add the times for that film using the films unique ID as the array keys, so as they loop through each one is added to the films id

So if i can remember the first method would look something like:

```php

$film_dates = [
    'Monday 10th February 2020' = [
         ['film'],
         ['film'],
         ['film'],
    ],
    'Tuesday 11th February 2020' = [...],
    'Wednesday 10th February 2020' = [...],
    ...
];
````

Then the second method loops through each of these days and sorts the films out in those days into the same film via id

```php

$film_dates = [
    'Monday 10th February 2020' = [
         ///--- you cousl possibly use the film title instead of the Film ID, just needs to be
        ///-- something that matches to group the film and its times.
         ['film ID'] => [
                  ['film details/times'],
                  ['film details/times'],
                  ['film details/times']
         ],
         ['film ID'] => [
                  ['film details/times'],
                  ['film details/times'],
                  ['film details/times']
         ],
    ],
    'Tuesday 11th February 2020' = [...],
    'Wednesday 10th February 2020' = [ ....],
    ...
];
````
Hope this helps you visualise the code :-)

**Comment by simondavies** [comment]
Sorry, No these are with in their own controller, and not part of this repo.  It's something I created to serve the site requirements, so you can add them to you file.

For instance could live within the Examples start.php file etc just  as methods etc 👍

**Comment by TheNewGuy16** [comment]
Hmm ok i am confused on how to use the methods and where to put them.  I dont have an example folder I just have a template page that I have modeled after one of the old example pages.  So that page right now is the listings by movie with the times for them kinda how you have your toggle feature on that one site one view is the listings by movie and I just need the listings by date.   but keep getting errors like expecting statement and the other was something about the not having a return statement or something.

**Comment by simondavies** [comment]
So on this page would you have something like

```php

require_once __DIR__ . '../../App/start.php';
/**
 * Get a list of all films
 */
$films = $Veezi->films();

//-- the rest of your site
```

Are you able to add example of it if possible mid not showing content you dont want to show.

**Comment by TheNewGuy16** [comment]
so this is my template page that list by movie

require_once __DIR__ . '/App/start.php';

use VeeziAPI\VeeziAPIWrapper as VeeziAPI;
$Veezi = new VeeziAPI(VEEZI_API_TOKEN);

/**
 * Get a list of all films
 */
$films = $Veezi->films();

<section class="section-wrapper movie-listing">
		<div class="container">
			<?php //-- lists films
            foreach ( $films as $film ) {
	            ?>
				<div class="row">
					<div class="col-4">
						<div class="movie-poster">
							<?php if ($film->getPoster()!= null){?>
								<div class="shadowed-image">
									<img class="img-fluid" src="<?php echo $film->getPoster();?>" alt="<?php echo $film->getTitle();?>" title="<?php echo $film->getTitle();?>" />
								</div>
							<?php }else{?>
								<div class="shadowed-image">
									<img class="img-fluid" src="<?php echo $film->getPosterThumb();?>" alt="<?php echo $film->getTitle();?>" title="<?php echo $film->getTitle();?>" />
								</div>
							<?php } ?>
						</div>
					</div>
					<div class="col-8">
						<h3 class="movie-title">
							<?php echo $film->getTitle(); ?>
						</h3>
						<div class="rating-length">
							<h4>Rated <?php echo $film->getRating()['rate']; ?> / <?php echo $film->getDuration();?> Mins</h4>
						</div>
						<div class="trailer-link">
							<div class="btn-style btn-raiseUp btn-shadow primaryColor-btn"><a target="_blank" href="<?php echo $film->getTrailerURL(); ?>">Show Trailer</a></div>
						</div>
						<div class="dolby-logo">

						</div>
						<div class="movie-desc">
						<p><?php echo $film->getSynopsis();?></p>
						</div>
						<div class="movie-times">
							<?php
							$film = $Veezi->selectedFilm($film->getId());
						    $film_start_dates = $film->getDatesAndTimes();
						    foreach ($film_start_dates as $date => $times) {
								echo '<h4>' . $date . '</h4>';
								echo '<ul class="btn-group" role="group" aria-label="">';
								foreach ($times as $time) {
									echo '<li><a class="movie-time" href="' . $time['link'] . '?siteToken=' . VEEZI_SITE_TOKEN . '" target="_blank">' . $time['time'] . '</a></li>';
								}
								echo '</ul>';
						        }
						         ?>
						</div>
					</div>
				</div>
			<?php } ?>
		</div>
</section>

So that works for the listing of times and ticket links by movies....is that what you needed to see

**Comment by TheNewGuy16** [comment]
So this is my template that list the movies out



require_once __DIR__ . '/App/start.php';

use VeeziAPI\VeeziAPIWrapper as VeeziAPI;
$Veezi = new VeeziAPI(VEEZI_API_TOKEN);

$films = $Veezi->films();


<section class="section-wrapper movie-listing">
		<div class="container">
			
            foreach ( $films as $film ) {
	            
				<div class="row">
					<div class="col-4">
						<div class="movie-poster">
							 if ($film->getPoster()!= null){
								<div class="shadowed-image">
									<img class="img-fluid" src=" echo $film->getPoster();" alt=" echo $film->getTitle();" title=" echo $film->getTitle();" />
								</div>
							 }else{
								<div class="shadowed-image">
									<img class="img-fluid" src=" echo $film->getPosterThumb();" alt=" echo $film->getTitle();" title=" echo $film->getTitle();" />
								</div>
							 } 
						</div>
					</div>
					<div class="col-8">
						<h3 class="movie-title">
							 echo $film->getTitle(); 
						</h3>
						<div class="rating-length">
							<h4>Rated  echo $film->getRating()['rate'];  /  echo $film->getDuration(); Mins</h4>
						</div>
						<div class="trailer-link">
							<div class="btn-style btn-raiseUp btn-shadow primaryColor-btn"><a target="_blank" href=" echo $film->getTrailerURL(); ">Show Trailer</a></div>
						</div>
						<div class="dolby-logo">

						</div>
						<div class="movie-desc">
						<p> echo $film->getSynopsis();</p>
						</div>
						<div class="movie-times">
							
							$film = $Veezi->selectedFilm($film->getId());
						    $film_start_dates = $film->getDatesAndTimes();
						    foreach ($film_start_dates as $date => $times) {
								echo '<h4>' . $date . '</h4>';
								echo '<ul class="btn-group" role="group" aria-label="">';
								foreach ($times as $time) {
									echo '<li><a class="movie-time" href="' . $time['link'] . '?siteToken=' . VEEZI_SITE_TOKEN . '" target="_blank">' . $time['time'] . '</a></li>';
								}
								echo '</ul>';
						        }
						         
						</div>
					</div>
				</div>
			 } 
		</div>
</section>

is that what you needed to see

**Comment by simondavies** [comment]
Thanks just need the top part of the first page :-)

**Comment by simondavies** [comment]
Ok its getting a little late here but I have tried to demo an I idea of how to use it but I think there could be errors, but hopefully it might give the idea of whats trying to happen.

```php
require_once __DIR__ . '/config.php';

//-- inittate the Veezi class
use VeeziAPI\VeeziAPIWrapper as VeeziAPI;

/**
 * STRAT HERE
 */
use VeeziAPI\Services\APIRequest;

$Veezi = new VeeziAPI(VEEZI_API_TOKEN);

$VeeziAPI = new APIRequest();

$allfilms = $VeeziAPI->request('websession');

//-- $films_by_day this should give you then the list of dates array
$films_by_day = getAllAvailableFilmsByDate($allfilms);


function getAllAvailableFilmsByDate($allfilms) {
    // -- Basically i get all the 'websession'
    $film_details = $allfilms;///-- notice this part as it changed from before
    $film_dates = [];
    //-- then I loop through them
    foreach ($film_details as $film) {
        //-- I then create carbon to create a date instance to help
        //- create the dates array
        $PreShowStartTime = Carbon::parse($film->PreShowStartTime);
        $day = $PreShowStartTime->format('l jS F Y');
        $time = $PreShowStartTime->format('H:i');
        $data = [
            'id' => $film->FilmId,
            'title' => $film->Title,
            //-- add what ever data you want with each film
            ....
        ];
        //-- Sort them into their restropective film Dates
        //-- As you can see im using the $day variable to create the array key
        //-- this then sorts them into days
        if (array_key_exists($day, $film_dates)) {
            $film_dates[$day][] = $data;
        } else {
            $film_dates[$day][] = $data;
        }

        //-- I then sort the array/result by the key
        //-- So its sorting by date.
        uksort($film_dates, function ($a, $b) {
            return strtotime($a) - strtotime($b);
        });

        //-- sort the films into their titles on the day and their bookable times/links
        return self::orderTheFilmsIntoTimes($film_dates);

    }
}

function orderTheFilmsIntoTimes($dates) {
    $day = [];
    $film_times = [];
    $count = 0;

    //-- loop through the day
    foreach ($dates as $date => $films) {
        //-- loop through films on that day
        foreach ($films as $film_index => $film) {
            $film_details = [
                'title' => $film['title'],
                'url' => $film['url'],
                'time' => $film['time'],
                ...
            ];

            //-- if title created then just add to it else create it first
            if (array_key_exists($date, $film_details)) {
                array_push($film_times[$film['id']], $film_details);
            } else {
                $film_times[$film['id']][] = $film_details;
            }
        }
        $day[$date] = $film_times;
        $film_times = [];
    }
    return $day;
}
/**
 * FINISH HERE
 */
```

If there is an issue try adding them to the VeeziAPIWrapper class as say

```php


///-- update this class
 class VeeziAPIWrapper extends APIRequest {

    function __construct(){...}
    public function films(){...}
    public function selectedFilm($film_id){....}
    /**
     * ADD HERE
     */
    public function filmsByDate(){
        $allfilms = self::selectedFilmWebSessions();
        return self::getAllAvailableFilmsByDate($allfilms);
    }
    protected function getAllAvailableFilmsByDate($allfilms){....}
    public function orderTheFilmsIntoTimes($dates){....}
    public function selectedFilmWebSessions()
    {
        return  parent::request('websession');
    }
 }

//-- so where you call currently
$films = $Veezi->films();

//-- tyr this way
$films = $Veezi->filmsByDate();
```

Mind you the later is probably the better method but the only issue is if / when I get back to the Github project any updates will wipe out what you have done.

Hope this aids your progress, let me know if still nothing then I will see what I can do to sort it out for you tomorrow after work etc.

**Comment by TheNewGuy16** [comment]
o thanks for trying I will see if i can make sense of it

here is the url if you want to see what I have outputting as of now before implementing the newest code

http://behinddoor1.com/showtimes/

**Comment by TheNewGuy16** [comment]
this is with a new controller and public function in the VeeziApiWrapper.php so i think it wouldnt  get overwritten but like i said cant get it to sort into dates but hopefully I can apply your methods

**Comment by simondavies** [comment]
Nice Like the design 👍I will check back tomorrow, thanks

**Comment by TheNewGuy16** [comment]
So not sure why but the second function was giving me problems so I added it to the first one so in my VeeziAPIWrapper.php i have

`public function filmsByDate(){
		$all_sessions = self::selectedFilmWebSessions();
		$film_dates = [];
		foreach ($all_sessions as $film) {
			//-- I then create carbon to create a date instance to help
			//- create the dates array
			$PreShowStartTime = Carbon::parse($film->PreShowStartTime);
			$day = $PreShowStartTime->format('l jS F Y');
			$time = $PreShowStartTime->format('h:i');
			$data = [
				'film_id' => $film->FilmId,
				'type' => $film->ShowType,
				'status' => $film->Status,
				'title' => $film->Title,
				'start' => $time,
				'feature_start' => new Carbon($film->FeatureStartTime),
				'feature_end' => new Carbon($film->FeatureEndTime),
				'end' => new Carbon($film->CleanupEndTime),
			];
			if (array_key_exists($day, $film_dates)) {
				$film_dates[$day][] = $data;
			} else {
				$film_dates[$day][] = $data;
			}
			uksort($film_dates, function ($a, $b) {
				return strtotime($a) - strtotime($b);
			});

		}
			return self::orderTheFilmsIntoTimes($film_dates);
	}`

**Comment by TheNewGuy16** [comment]
So not sure why but the second function when called from the first function was just erroring out so I just added it to the first function so this is what i have in my VeeziAPIWrapper.php file


```php
public function filmsByDate(){
		$all_sessions = self::selectedFilmWebSessions();
		$film_dates = [];
		foreach ($all_sessions as $film) {
			//-- I then create carbon to create a date instance to help
			//- create the dates array
			$PreShowStartTime = Carbon::parse($film->PreShowStartTime);
			$day = $PreShowStartTime->format('l jS F Y');
			$time = $PreShowStartTime->format('h:i');
			$data = [
				'film_id' => $film->FilmId,
				'type' => $film->ShowType,
				'status' => $film->Status,
				'title' => $film->Title,
				'start' => $time,
				'feature_start' => new Carbon($film->FeatureStartTime),
				'feature_end' => new Carbon($film->FeatureEndTime),
				'end' => new Carbon($film->CleanupEndTime),
			];
			if (array_key_exists($day, $film_dates)) {
				$film_dates[$day][] = $data;
			} else {
				$film_dates[$day][] = $data;
			}
			uksort($film_dates, function ($a, $b) {
				return strtotime($a) - strtotime($b);
			});

		}
			return self::orderTheFilmsIntoTimes($film_dates);
	}
public function orderTheFilmsIntoTimes($dates) {
		$day = [];
		$film_times = [];
		$count = 0;

		//-- loop through the day
		foreach ($dates as $date => $films) {
			//-- loop through films on that day
			foreach ($films as $film_id => $film) {
				$film_details = [
					'title' => $film['title'],
					'url' => $film['url'],
					'time' => $film['time'],
				];

				//-- if title created then just add to it else create it first
				if (array_key_exists($date, $film_details)) {
					array_push($film_times[$film['film_id']], $film_details);
				} else {
					$film_times[$film['film_id']][] = $film_details;
				}
			}
			$day[$date] = $film_times;
			$film_times = [];
		}
		return $day;
	}
	public function selectedFilmWebSessions()
	{
		return  parent::request('websession');
	}

```

you can see in the second function where by the comment 	" if title created then just add to it else create it first" I had to change the 
```php
if (array_key_exists($date, $film_details)) {
					array_push($film_times[$film['id']], $film_details);
				} else {
					$film_times[$film['id']][] = $film_details;
				}
```
to
```php
if (array_key_exists($date, $film_details)) {
					array_push($film_times[$film['film_id']], $film_details);
				} else {
					$film_times[$film['film_id']][] = $film_details;
				}
```
basically changed he 'id' to 'film_id' and no it only pulls in the five movies for each date instead of just one the only thing is i cant get the tiles or url or times to show up.
here is the mark up for the template file
```php
$filmsByDate = $Veezi->filmsByDate();
var_dump($filmsByDate);?>
<ul>
<?php foreach ($filmsByDate as $day => $film){?>
	<li>
		<?php echo $day?>
		<ul>
			<?php foreach($film as $film_id => $movie){?>
				<li><?php echo $movie['title'] ?> | <?php echo $movie['start'] ?></li>
			<?php }?>
		</ul>
	</li>
<?php }?>
</ul>
```
You can see the var_dump at http://behinddoor1.com/showtimes/
```
array(4) { ["Monday 10th February 2020"]=> array(3) { ["ST00000026"]=> array(1) { [0]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } } ["ST00000022"]=> array(1) { [0]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } } ["ST00000030"]=> array(1) { [0]=> array(3) { ["title"]=> string(8) "Parasite" ["url"]=> NULL ["time"]=> NULL } } } ["Tuesday 11th February 2020"]=> array(5) { ["ST00000026"]=> array(4) { [0]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [3]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } } ["ST00000024"]=> array(3) { [0]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } } ["ST00000022"]=> array(4) { [0]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [3]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } } ["ST00000028"]=> array(2) { [0]=> array(3) { ["title"]=> string(11) "Jojo Rabbit" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(11) "Jojo Rabbit" ["url"]=> NULL ["time"]=> NULL } } ["ST00000030"]=> array(2) { [0]=> array(3) { ["title"]=> string(8) "Parasite" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(8) "Parasite" ["url"]=> NULL ["time"]=> NULL } } } ["Wednesday 12th February 2020"]=> array(5) { ["ST00000026"]=> array(4) { [0]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [3]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } } ["ST00000024"]=> array(3) { [0]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } } ["ST00000022"]=> array(4) { [0]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [3]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } } ["ST00000028"]=> array(2) { [0]=> array(3) { ["title"]=> string(11) "Jojo Rabbit" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(11) "Jojo Rabbit" ["url"]=> NULL ["time"]=> NULL } } ["ST00000030"]=> array(2) { [0]=> array(3) { ["title"]=> string(8) "Parasite" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(8) "Parasite" ["url"]=> NULL ["time"]=> NULL } } } ["Thursday 13th February 2020"]=> array(5) { ["ST00000026"]=> array(4) { [0]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } [3]=> array(3) { ["title"]=> string(4) "1917" ["url"]=> NULL ["time"]=> NULL } } ["ST00000024"]=> array(3) { [0]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(17) "Bad Boys for Life" ["url"]=> NULL ["time"]=> NULL } } ["ST00000022"]=> array(4) { [0]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [2]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } [3]=> array(3) { ["title"]=> string(15) "Gretel & Hansel" ["url"]=> NULL ["time"]=> NULL } } ["ST00000028"]=> array(2) { [0]=> array(3) { ["title"]=> string(11) "Jojo Rabbit" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(11) "Jojo Rabbit" ["url"]=> NULL ["time"]=> NULL } } ["ST00000030"]=> array(2) { [0]=> array(3) { ["title"]=> string(8) "Parasite" ["url"]=> NULL ["time"]=> NULL } [1]=> array(3) { ["title"]=> string(8) "Parasite" ["url"]=> NULL ["time"]=> NULL } } } }
```
but the urls and times are just null so cant figure out what I am doing wrong here.  But your example you sent me is exactly what I need, I just cant get the info for the movies listed correctly

**Comment by simondavies** [comment]
Hi I think the issue is in the following:

```php
public function orderTheFilmsIntoTimes($dates) {
  .....
     $film_details = [
	'title' => $film['title'],
	'url' => $film['url'],
	'time' => $film['time'],
   ];
...
}
```
The data for these comes from the first function and the:

```php
   $data = [
	'film_id' => $film->FilmId,
	'type' => $film->ShowType,
	'status' => $film->Status,
	'title' => $film->Title,
	'start' => $time,
	'feature_start' => new Carbon($film->FeatureStartTime),
	'feature_end' => new Carbon($film->FeatureEndTime),
	'end' => new Carbon($film->CleanupEndTime),
  ];
```

As you are looking for ` $film['url']` there is not `url` index in the `$data` so you will need to add the array values within the `$data` for `url` and `time` etc. 

So i might have missed it in my examples but if your try adding the following to the `$data` array in the `filmsByDate` function

```php
    'url' => $film->Url,
    'day' => $day,
    'time' => $time,
```

so the full array could be:

```php
   $data = [
	'film_id' => $film->FilmId,
	'type' => $film->ShowType,
	'status' => $film->Status,
	'title' => $film->Title,
	'url' => $film->Url,
	'day' => $day,
	'time' => $time,
	'start' => $time,
	'feature_start' => new Carbon($film->FeatureStartTime),
	'feature_end' => new Carbon($film->FeatureEndTime),
	'end' => new Carbon($film->CleanupEndTime),
  ];
```

hope this helps.

**Comment by TheNewGuy16** [comment]
So i got it to out put and be ordered you can see it at
http://behinddoor1.com/showtimes/

**Comment by TheNewGuy16** [comment]
no i have to just get all the movie details in place.

**Comment by simondavies** [comment]
Great to hear, just erroring for me now, hoep you egt it sorted.

**Comment by TheNewGuy16** [comment]
yeah trying to get the film details controller I made to work

**Comment by TheNewGuy16** [comment]
So I got the dates and details and time listing all set up I am going through the files and organize a little more but should I just fork this project and add them here that way or is there a way to add them to this main project? check it out http://behinddoor1.com/showtimes/

**Comment by simondavies** [comment]
Hi I would fork them as this be best and also a way for me check out the sholw structure etc, otherwise submit some pull requests if you like 👍
