### ISSUE TITLE
Cant get times to sort in order

### ISSUE THREAD

**Issue by TheNewGuy16** [simondavies/Veezi-API-Wrapper#11]
Hey trying to sort my times in order but for some reason they are out of order I did change the time format to 12 hours so maybe that has something to do with it?

the link  for the page is
https://riverwalktheater.com/showtimes/

**Comment by simondavies** [comment]
Cannot see any films to view the dates?  It links out to the veezi listings page. I tend to turn things into timestamps as they are easier to sort

**Comment by TheNewGuy16** [comment]
Yeah I ended up getting it but the load time was huge and the bossman
wasnt happy so I could cache things or some thing but as of now i am
rebuilding with jquery



Brian Musinski
Avid Design
P.O. Box 691
vail, CO 81658
t: 970.479.8555
f: 970.479.6007
http://avidonline.com

WEB.PRINT.IDEAS

Follow Avid Design on:
Facebook <https://www.facebook.com/aviddesign> | Twitter
<http://twitter.com/avid_design> | Google+
<https://plus.google.com/103558248328328505381/posts> | Pinterest
<http://pinterest.com/aviddesignvail/> | LinkedIn
<http://www.linkedin.com/company/avid-design-vail>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by simondavies** [comment]
Ah! OK. Yeah! for the site i did it for I built it with Laravel and heavily cached the pages, as load times just to do the times/dates can be massive, the complexity of the veezi api.  I am hoping they simplify it one day and create a ideal API. As its not ideal for the web still.

Things like the poster, synopsis etc i store on the site DB adn just call in the times/dates.

**Comment by TheNewGuy16** [comment]
yeah i am not sure i am doing it all correctly but I am just pluging right
into the veezi api with ajax  then on page load populate the first date
films. Then every date click after that load that dates films....so
hopefully I am doing it right.  I am so use to coding in php that making
arrays and loop through them in jquery was a little tough to remember but
its coming along



Brian Musinski
Avid Design
P.O. Box 691
vail, CO 81658
t: 970.479.8555
f: 970.479.6007
http://avidonline.com

WEB.PRINT.IDEAS

Follow Avid Design on:
Facebook <https://www.facebook.com/aviddesign> | Twitter
<http://twitter.com/avid_design> | Google+
<https://plus.google.com/103558248328328505381/posts> | Pinterest
<http://pinterest.com/aviddesignvail/> | LinkedIn
<http://www.linkedin.com/company/avid-design-vail>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by simondavies** [comment]
Cool, 👍 yeah haven't touched jQuery in yonks, do vanilla or vuejs, go luck
