### ISSUE TITLE
Not able to get the poster.

### ISSUE THREAD

**Issue by sanchula** [simondavies/Veezi-API-Wrapper#3]
I am not able to display the poster.  Can some one help me.

**Comment by simondavies** [comment]
Hello, unfortunately as of present Veezi do not enable the poster on their end for display, through their API. If linking directly then you need to be logged in as it's behind their private server. And this is not an ideal situation. They have said to me to a similar query last year, that they will have a look and consider making it's accessible. But for now, it's not possible.

What I do, is using the API to create say a film(s) and save various details to a sites main database, then I have coded it to upload a poster site cms end.  I then use the Veezi API  to keep the film dates and various details updated.

So save the title, synopsis and whatever you need to the sites main DB, and also upload a poster for this image, where its all stored in the local DB.

Then use the Veezi system to return the dates/times when and where required, so ensuring at least the dates are updated if altered.

I hope this helps, a little.
