### ISSUE TITLE
Very slow to extract the page

### ISSUE THREAD

**Issue by sanchula** [simondavies/Veezi-API-Wrapper#5]
Hi 

I have used this wrapper and developed my website.  the site is www.dccinemas.com/digimax/index_new.php.

I have developed Now Showing, Show Times and Coming Soon using the the Wrapper code.  It takes long time than vix ticketing.

Here am I missing any thing or how can i improve the performance.
If someone need I can share the code.

Thanks
Raman Sanchula

**Comment by simondavies** [comment]
Hello, Sorry for the late reply as have only seen this and did not get a notification about it so appologise, if this is still being used or issue let me know
