### ISSUE TITLE
no autoload_static.php file

### ISSUE THREAD

**Issue by TheNewGuy16** [simondavies/Veezi-API-Wrapper#6]
I had the wrapper working a little bit but then I figured I would reinstall it and now I am getting this error.

require_once(/var/www/vhosts/behinddoor1.com/httpdocs/wp-content/plugins/Veezi-API-Wrapper-master/vendor/composer/autoload_static.php): failed to open stream: No such file or directory in /var/www/vhosts/behinddoor1.com/httpdocs/wp-content/plugins/Veezi-API-Wrapper-master/vendor/composer/autoload_real.php on line 28

any ideas?

**Comment by simondavies** [comment]
Hello @TheNewGuy16 thasnk for the response.  It might be that you need to run `composer dump-autoload` seems the autoload files generated might be missing.

**Comment by TheNewGuy16** [comment]
Do I need to be in the vendor folder or just the veezi api wrapper folder

**Comment by TheNewGuy16** [comment]
So I tried the dump-autoload but no new files are generated.  Is there another solution?

**Comment by simondavies** [comment]
Where are you trying to run the `composer dump-autoload` have you got composer running else where like on the root of the project or just using this, as I see your using it as a WP plugin. else I would run it directly in the `veezi api wrapper` folder, as composer will create the vendor folder for you. and setup the autoload files.

whats the terminal output etc

**Comment by TheNewGuy16** [comment]
The out put I get is

  [Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, yo
  u can disable this error, at your own risk, by setting the 'disable-tls' option to true.


dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--no-dev]

**Comment by TheNewGuy16** [comment]
I had it working but there where other errors like some count error so I redownloaded it from git hub thinking maybe something changed and now I cant get it to activate again

**Comment by simondavies** [comment]
this might be a composer issue [Composer NOSSL Issue](https://github.com/composer/composer/issues/6031)  regarding this output.

`count error` might be a php version issue, what version of php are you using.

**Comment by TheNewGuy16** [comment]
Is there any way you can add the file to your git directory since it is not there either? or is it suppose to be generated after I do composer update....which I have done but no change

**Comment by simondavies** [comment]
Yeah, composer files / venodr directories will only be added once you run composer, its never recommended to add vendor files to the project as they can be huge etc.


with out seeing the whole set up and being able to set it up locally will need to try and help otherwayse.

**Comment by TheNewGuy16** [comment]
my php version is PHP 7.1.32 (cli) (built: Aug 28 2019 09:08:22) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by TheNewGuy16** [comment]
ok I am a little new to all of this composer stuff so not sure how to figure all this out

**Comment by simondavies** [comment]
just downloading now and trying it locally seeing if i get anything.

**Comment by TheNewGuy16** [comment]
yeah if i just download and try to look at the example folders it gives me the same error about the autoload_static.php

**Comment by simondavies** [comment]
Well got it to work on without issues locally.
try and deleting the file called  `composer.lock`, and then run `composer update`  to try and get all the latest files.

**Comment by simondavies** [comment]
this is what i did to get it running locally if this helps.

`composer create-project simondavies/veezi-api-wrapper veeziapi`

`cd veeziapi` - went into the folder

delete the `composer.lock` file

then run `composer install`

you shoudl get the message `Carbon 1 is deprecated, see how to migrate to Carbon 2` so you can update this if you want by running `./vendor/bin/upgrade-carbon` then selecting yes when asked.

Once this is all run I then visited the local version in chrome.
`http://veeziapi.test/Examples`

And he page loaded fine no issues.

Hope this helps.

**Comment by TheNewGuy16** [comment]
ok I will give it a go I just moved my project files to my computer instead of working of our server so hopefully that solves the open ssl issue and will hopefully be able to create project

**Comment by simondavies** [comment]
Cool, agree bets to try locally first. Will keep this open let me know how it goes

**Comment by TheNewGuy16** [comment]
sweet had to set up my local php7 a little more to get composer to install but it is working now so yu can close this one but I do have more questions so I will start a new thread

**Comment by simondavies** [comment]
No worries, glad its helping.
