### ISSUE TITLE
How to Deploy

### ISSUE THREAD

**Issue by TheNewGuy16** [simondavies/Veezi-API-Wrapper#7]
What is the proper why to deploy?  What files need to go on the live server? Do i just load the whole folder with the vendors and everything?

**Comment by simondavies** [comment]
Normally best to install via composer but you can upload the files, but the vendor file can take a while to uploaded. dependant on your sites and it structure you might have to alter some files like the paths etc

**Comment by TheNewGuy16** [comment]
ok so I use ssh usually so wasn't hard to get the plugin installed and activated.  Just new to the composer so didnt know if it had some production output like webpack and gulp

**Comment by simondavies** [comment]
nothing like that, just need to make sure to edit a config file for the veezi credentials etc

**Comment by TheNewGuy16** [comment]
Sweet its all working then....just need to get the rest of the info in place for the listings.  Thanks for helping out

**Comment by simondavies** [comment]
No worries, ill probably be away for a while [sleep and work :-)] but will try to answer when i can.
