### ISSUE TITLE
Extra character at line 312  guzzle functions.php

### ISSUE THREAD

**Issue by TheNewGuy16** [simondavies/Veezi-API-Wrapper#8]
This is an "e" on line 312 that's is making the wrapper throw an error on the live server
/vendor/guzzlehttp/promises/src/functions.php line 312

**Comment by simondavies** [comment]
unfortunately `/vendor/guzzlehttp` is a vendor file that is a dependant and those in the vendor file are ones I do not have control of, so you would need to do research on that error for that package. Bit do share the full error message to help further

**Comment by simondavies** [comment]
got a link to the live site throwing the error

**Comment by TheNewGuy16** [comment]
I already removed the character and it is working now.  Do you want me to revert it so you can see?

**Comment by simondavies** [comment]
no if you got it working that ok.
