### ISSUE TITLE
No times on the example film.php

### ISSUE THREAD

**Issue by TheNewGuy16** [simondavies/Veezi-API-Wrapper#9]
Trying to figure out how to get the btn links and times for the individual films to show up.  Ideally I want them on the film listing page grouped by days, but I cant even get them to work in the example files.

**Comment by TheNewGuy16** [comment]
ok I figured it out. for the films in the veezi admin you have to have them as open not planned

**Comment by TheNewGuy16** [comment]
Is so I am trying to duplicate the time structure that you use for the single film page into the films listing page but I cant get it to work would you know how to get the times to be in the films listings page?

**Comment by simondavies** [comment]
Hello, basically you would need to call the single film class for each output of film in the listings loop.
With out testing or trying, something like.

```php
$films = $Veezi->films();

foreach ($films as $film) {
    $film = $Veezi->selectedFilm($film->getId());
   $film_start_dates = $film->getDatesAndTimes();
    echo '<h3>' . $film->getTitle() . '</h3>'
   foreach ($film_start_dates as $date => $times) {
	echo '<h5>' . $date . '</h5>';
	echo '<div class="btn-group" role="group" aria-label="">';
	foreach ($times as $time) {
		echo '<a class="btn btn-info" 
                                href="' . $time['link'] . '?siteToken=' . VEEZI_SITE_TOKEN . '" 
                                target="_blank">' . $time['time'] . '</a>';
	}
	echo '</div>';
   }
}
```

So something like this, basically taking the films and film code and mashing it. Bu tI would be a little weary on this as the way Veezi API is constructed it can cause slow response and server time outs etc.

But I hope this gives you a clue etc

**Comment by TheNewGuy16** [comment]
I cant even explain how thankful I am for you help it totally works now. I
dont know what I was doing wrong cause it seemed like I tried that but it
didnt work....but your code does.


Brian Musinski
Avid Design
P.O. Box 691
vail, CO 81658
t: 970.479.8555
f: 970.479.6007
http://avidonline.com

WEB.PRINT.IDEAS

Follow Avid Design on:
Facebook <https://www.facebook.com/aviddesign> | Twitter
<http://twitter.com/avid_design> | Google+
<https://plus.google.com/103558248328328505381/posts> | Pinterest
<http://pinterest.com/aviddesignvail/> | LinkedIn
<http://www.linkedin.com/company/avid-design-vail>

**Comment by simondavies** [comment]
Glad to help 👍
